version: '3'

services:
  web:
    image: nginx-webdav
    build: .
    container_name: nginx-webdav
    volumes:
      - $PWD/htpasswd:/htpasswd:ro
      - webdav:/webdav
      # - $PWD/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80

volumes:
  webdav:
    driver: local